name: GraalVM Native Image Test run and build tests
on: [pull_request, workflow_dispatch]
jobs:
  build:
    name: test and compile on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    env:
      ZCMI_SANDBOX_URL: ${{ secrets.ZCMI_SANDBOX_URL }}
      ZCMI_ADMIN_EMAIL: ${{ secrets.ZCMI_ADMIN_EMAIL }}
      ZCMI_ADMIN_TOKEN: ${{ secrets.ZCMI_ADMIN_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: graalvm/setup-graalvm@54b4f5a65c1a84b2fdfdc2078fe43df32819e4b1 # v1.4.5
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          native-image-pr-reports: 'true'
      - name: call gradle to run tests and then compile
        if: matrix.os == 'ubuntu-latest'
        run: ./gradlew test sonar nativeCompile
      - name: call gradle to run tests and then compile
        if: matrix.os != 'ubuntu-latest'
        run: ./gradlew test nativeCompile
      - name: upload binary
        uses: actions/upload-artifact@v4
        with:
          name: zcmi-${{ matrix.os }}
          path: build/native/nativeCompile/zcmi*
